package com.picman.picman.Endpoints;

import com.picman.picman.AssignationMgmt.AssignationServiceImplementation;
import com.picman.picman.CategoriesMgmt.Category;
import com.picman.picman.CategoriesMgmt.CategoryServiceImplementation;
import com.picman.picman.Exceptions.*;
import com.picman.picman.LoggingMgmt.Log;
import com.picman.picman.LoggingMgmt.LogServiceImplementation;
import com.picman.picman.PicturesMgmt.Picture;
import com.picman.picman.PicturesMgmt.PictureServiceImplementation;
import com.picman.picman.SpringSettings.Settings;
import com.picman.picman.SpringSettings.SettingsService;
import com.picman.picman.UserMgmt.User;
import com.picman.picman.UserMgmt.UserServiceImplementation;
import com.picman.picman.Utilities.Utilities;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;

import java.security.SecureRandom;
import java.time.LocalDateTime;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Set;

@Controller
@RequestMapping("cn/admin/")
public class AdminDashboard {

    private final UserServiceImplementation userService;
    private final PasswordEncoder passwordEncoder;
    private final LogServiceImplementation logService;
    private final PictureServiceImplementation pictureService;
    private final AssignationServiceImplementation assignationService;
    private final SettingsService settingsService;
    private final CategoryServiceImplementation categoryService;

    public AdminDashboard(UserServiceImplementation usi, PasswordEncoder pe, LogServiceImplementation lsi, PictureServiceImplementation psi, AssignationServiceImplementation asi, SettingsService ss, CategoryServiceImplementation csi) {
        this.userService = usi;
        this.passwordEncoder = pe;
        this.logService = lsi;
        this.pictureService = psi;
        this.assignationService = asi;
        this.settingsService = ss;
        this.categoryService = csi;
    }

    @GetMapping("/")
    public String root() {
        return "cn/admin/dashboard";
    }

    @GetMapping("/dashboard")
    public String dashboard(Model model) {
        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        User main = userService.findByEmail(((org.springframework.security.core.userdetails.User) auth.getPrincipal()).getUsername());

        LinkedHashMap<Picture, List<Integer>> pcbind = new LinkedHashMap<>();
        LinkedHashMap<Category, List<Long>> cpsbind = new LinkedHashMap<>();
        LinkedHashMap<String, String> settings = new LinkedHashMap<>();

        for (Picture p : pictureService.getAllOrdered()) {
            pcbind.put(
                    p,
                    assignationService.getCategoriesByPictureId(p.getId()).stream().map(Category::getId).toList()
            );
        }

        for (Category c : categoryService.findAll().stream().sorted(Comparator.comparing(Category::getId)).toList()) {
            cpsbind.put(
                    c,
                    assignationService.getPicturesByCategory(c)
            );
        }

        for (String key : settingsService.getAll().keySet().stream().sorted().toList()) {
            settings.put(key, settingsService.get(key));
        }

        model.addAttribute("current", main);
        model.addAttribute("users", userService.findAll());
        model.addAttribute("pictures", pictureService.findAll());
        model.addAttribute("cpsbind", cpsbind);
        model.addAttribute("pcbind", pcbind);
        model.addAttribute("roles", Utilities.Constants.privileges);
        model.addAttribute("logs", logService.findAll());
        model.addAttribute("settings", settings);
        model.addAttribute("path", "/ admin dashboard");
        return "cn/admin/dashboard";
    }

    @PostMapping("/create-user")
    public String createUser(@RequestParam("name") String name,@RequestParam("email") String email,@RequestParam("organization") String organization) throws InvalidFormParamException {
        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        User main = userService.findByEmail(((org.springframework.security.core.userdetails.User) auth.getPrincipal()).getUsername());

        // Testing whether parameters are valid
        String tname = Utilities.testUsername(name);
        String temail = Utilities.testEmail(email);
        String torganization = Utilities.testOrganization(organization);

        // Creating new user with autogenerated cryptographically secure password
        User u = new User(
                tname,
                temail,
                "TEMPPSW_" + passwordEncoder.encode(String.valueOf(new SecureRandom().nextInt())),
                Set.of('r'),
                torganization
        );
        User saved = userService.save(u);

        // Logging
        Log l = new Log(
                LocalDateTime.now(),
                "/cn/admin/create-user",
                "AdminDashboard",
                main,
                "User " + main.getId() + " created user " + saved.getId()
        );
        logService.save(l);

        return "redirect:/cn/admin/dashboard";
    }

    @ResponseBody
    @PostMapping("/edit-privileges")
    public void editUserPrivileges(@RequestParam("user") String id, @RequestParam("role") String role, @RequestParam("nowchecked") String assign) throws InvalidFormParamException {
        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        User main = userService.findByEmail(((org.springframework.security.core.userdetails.User) auth.getPrincipal()).getUsername());

        // Testing whether parameters are valid
        long uid = Utilities.testUserID(id);
        char urole = Utilities.testPrivilege(role);
        boolean uassign = Utilities.testGenericBoolean(assign);

        // Finding user in the repo and editing privileges
        User u = userService.findById(uid);
        if (u == null) throw new EntityNotFoundException(AdminDashboard.class, "User " + uid + " not found");
        userService.editPrivileges(u, urole, uassign);

        // Logging
        Log l = new Log(
                LocalDateTime.now(),
                "/cn/admin/edit-privileges",
                "AdminDashboard",
                main,
                "User " + main.getId() + (uassign?" added " : " removed ") + "privilege " + urole + (uassign?" to " : " from ") + " user " + uid

        );
        logService.save(l);
    }

    @GetMapping("/delete-user")
    public String deleteUser(@RequestParam("id") long id) {
        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        User main = userService.findByEmail(((org.springframework.security.core.userdetails.User) auth.getPrincipal()).getUsername());

        // Finding user in the repo
        User u = userService.findById(id);
        if (u == null) throw new EntityNotFoundException(AdminDashboard.class, "Could not find user with id " + id);

        // Check if trying to delete superadmin
        if (Settings.get("super_admin_id").equals(String.valueOf(id))) {
            throw new AccessDeniedException("Cannot delete superadmin user via application, database usage needed.");
        }
        userService.deleteById(id);

        // Logging
        Log l = new Log(
                LocalDateTime.now(),
                "/cn/admin/delete-user",
                "AdminDashboard",
                main,
                "User " + main.getId() + " deleted user " + u.getId()
        );
        logService.save(l);

        return "cn/admin/dashboard";
    }

    @GetMapping("/reset-psw")
    public String resetUserPsw(@RequestParam("id") long id) {
        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        User main = userService.findByEmail(((org.springframework.security.core.userdetails.User) auth.getPrincipal()).getUsername());

        // Finding user in the repo
        User u = userService.findById(id);
        if (u == null) throw new EntityNotFoundException(AdminDashboard.class, "Could not find user with id " + id);

        // Check if trying to reset superadmin password
        if (Settings.get("super_admin_id").equals(String.valueOf(id))) {
            throw new AccessDeniedException("Cannot reset superadmin password, database usage needed.");
        }
        u.setPassword("TEMPPSW_" + passwordEncoder.encode(String.valueOf(new SecureRandom().nextInt())));
        userService.save(u);

        // Logging
        Log l = new Log(
                LocalDateTime.now(),
                "/cn/admin/reset-psw",
                "AdminDashboard",
                main,
                "User " + main.getId() + " resetted password of user " + u.getId()
        );
        logService.save(l);

        return "redirect:/cn/admin/dashboard";
    }

    @GetMapping("/protect-picture")
    public String protectPicture(@RequestParam("pic-id") int id) {
        Picture p = pictureService.getById(id);
        if (p == null) {
            throw new ImageProcessingException("An error happened while processing the image");
        }
        p.setProtection(!p.isProtection());
        pictureService.save(p);

        return "redirect:/cn/admin/dashboard";
    }
}
